config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show]
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'new2', to: 'pages#new2'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: 'pages#home'
end

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p><%= number_to_phone "122000000" %></p>
<p><%= number_to_currency "122000000" %></p>
<p><%= number_to_percentage "99.9" %></p>

app/views/pages/home.html.erb
<h1>Hello <%= current_user.first_name %></h1>
<p>Find me in app/views/pages/home.html.erb</p>

<%# current_user.creat_usr %>

<h1>Posts</h1>
<%= @blogs.inspect %>

<h1>Skills</h1>
<%= @skills.inspect %>

<hr>

app/views/pages/new2.html.erb
<h2>Sign up</h2>



<%= form_for(:user, :url => session_path(:user)) do |f| %>


  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>